<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJF7aSfR\srcApp_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJF7aSfR/srcApp_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerJF7aSfR.legacy');

    return;
}

if (!\class_exists(srcApp_KernelProdContainer::class, false)) {
    \class_alias(\ContainerJF7aSfR\srcApp_KernelProdContainer::class, srcApp_KernelProdContainer::class, false);
}

return new \ContainerJF7aSfR\srcApp_KernelProdContainer([
    'container.build_hash' => 'JF7aSfR',
    'container.build_id' => '67ce26ae',
    'container.build_time' => 1581919443,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJF7aSfR');
