<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVLrxGUf\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVLrxGUf/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVLrxGUf.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVLrxGUf\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerVLrxGUf\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'VLrxGUf',
    'container.build_id' => 'c56e4f75',
    'container.build_time' => 1581921621,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVLrxGUf');
