<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Pointages extends \App\Entity\Pointages implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Pointages' . "\0" . 'rowid', '' . "\0" . 'App\\Entity\\Pointages' . "\0" . 'fkEmployer', '' . "\0" . 'App\\Entity\\Pointages' . "\0" . 'pointageArrivee', '' . "\0" . 'App\\Entity\\Pointages' . "\0" . 'noteArrivee', '' . "\0" . 'App\\Entity\\Pointages' . "\0" . 'pointageDepart', '' . "\0" . 'App\\Entity\\Pointages' . "\0" . 'noteDepart', '' . "\0" . 'App\\Entity\\Pointages' . "\0" . 'actif', '' . "\0" . 'App\\Entity\\Pointages' . "\0" . 'fkUserAuthor', '' . "\0" . 'App\\Entity\\Pointages' . "\0" . 'creeLe', '' . "\0" . 'App\\Entity\\Pointages' . "\0" . 'fkUserModif', '' . "\0" . 'App\\Entity\\Pointages' . "\0" . 'modifieLe', '' . "\0" . 'App\\Entity\\Pointages' . "\0" . 'description', '' . "\0" . 'App\\Entity\\Pointages' . "\0" . 'etat', '' . "\0" . 'App\\Entity\\Pointages' . "\0" . 'totalMinute'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Pointages' . "\0" . 'rowid', '' . "\0" . 'App\\Entity\\Pointages' . "\0" . 'fkEmployer', '' . "\0" . 'App\\Entity\\Pointages' . "\0" . 'pointageArrivee', '' . "\0" . 'App\\Entity\\Pointages' . "\0" . 'noteArrivee', '' . "\0" . 'App\\Entity\\Pointages' . "\0" . 'pointageDepart', '' . "\0" . 'App\\Entity\\Pointages' . "\0" . 'noteDepart', '' . "\0" . 'App\\Entity\\Pointages' . "\0" . 'actif', '' . "\0" . 'App\\Entity\\Pointages' . "\0" . 'fkUserAuthor', '' . "\0" . 'App\\Entity\\Pointages' . "\0" . 'creeLe', '' . "\0" . 'App\\Entity\\Pointages' . "\0" . 'fkUserModif', '' . "\0" . 'App\\Entity\\Pointages' . "\0" . 'modifieLe', '' . "\0" . 'App\\Entity\\Pointages' . "\0" . 'description', '' . "\0" . 'App\\Entity\\Pointages' . "\0" . 'etat', '' . "\0" . 'App\\Entity\\Pointages' . "\0" . 'totalMinute'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Pointages $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getRowid(): ?string
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getRowid();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRowid', []);

        return parent::getRowid();
    }

    /**
     * {@inheritDoc}
     */
    public function getFkEmployer(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFkEmployer', []);

        return parent::getFkEmployer();
    }

    /**
     * {@inheritDoc}
     */
    public function setFkEmployer(int $fkEmployer): \App\Entity\Pointages
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFkEmployer', [$fkEmployer]);

        return parent::setFkEmployer($fkEmployer);
    }

    /**
     * {@inheritDoc}
     */
    public function getPointageArrivee(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPointageArrivee', []);

        return parent::getPointageArrivee();
    }

    /**
     * {@inheritDoc}
     */
    public function setPointageArrivee(?\DateTimeInterface $pointageArrivee): \App\Entity\Pointages
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPointageArrivee', [$pointageArrivee]);

        return parent::setPointageArrivee($pointageArrivee);
    }

    /**
     * {@inheritDoc}
     */
    public function getNoteArrivee(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNoteArrivee', []);

        return parent::getNoteArrivee();
    }

    /**
     * {@inheritDoc}
     */
    public function setNoteArrivee(?string $noteArrivee): \App\Entity\Pointages
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNoteArrivee', [$noteArrivee]);

        return parent::setNoteArrivee($noteArrivee);
    }

    /**
     * {@inheritDoc}
     */
    public function getPointageDepart(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPointageDepart', []);

        return parent::getPointageDepart();
    }

    /**
     * {@inheritDoc}
     */
    public function setPointageDepart(?\DateTimeInterface $pointageDepart): \App\Entity\Pointages
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPointageDepart', [$pointageDepart]);

        return parent::setPointageDepart($pointageDepart);
    }

    /**
     * {@inheritDoc}
     */
    public function getNoteDepart(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNoteDepart', []);

        return parent::getNoteDepart();
    }

    /**
     * {@inheritDoc}
     */
    public function setNoteDepart(?string $noteDepart): \App\Entity\Pointages
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNoteDepart', [$noteDepart]);

        return parent::setNoteDepart($noteDepart);
    }

    /**
     * {@inheritDoc}
     */
    public function getActif(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActif', []);

        return parent::getActif();
    }

    /**
     * {@inheritDoc}
     */
    public function setActif(bool $actif): \App\Entity\Pointages
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActif', [$actif]);

        return parent::setActif($actif);
    }

    /**
     * {@inheritDoc}
     */
    public function getFkUserAuthor(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFkUserAuthor', []);

        return parent::getFkUserAuthor();
    }

    /**
     * {@inheritDoc}
     */
    public function setFkUserAuthor(?int $fkUserAuthor): \App\Entity\Pointages
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFkUserAuthor', [$fkUserAuthor]);

        return parent::setFkUserAuthor($fkUserAuthor);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreeLe(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreeLe', []);

        return parent::getCreeLe();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreeLe(\DateTimeInterface $creeLe): \App\Entity\Pointages
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreeLe', [$creeLe]);

        return parent::setCreeLe($creeLe);
    }

    /**
     * {@inheritDoc}
     */
    public function getFkUserModif(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFkUserModif', []);

        return parent::getFkUserModif();
    }

    /**
     * {@inheritDoc}
     */
    public function setFkUserModif(?int $fkUserModif): \App\Entity\Pointages
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFkUserModif', [$fkUserModif]);

        return parent::setFkUserModif($fkUserModif);
    }

    /**
     * {@inheritDoc}
     */
    public function getModifieLe(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getModifieLe', []);

        return parent::getModifieLe();
    }

    /**
     * {@inheritDoc}
     */
    public function setModifieLe(?\DateTimeInterface $modifieLe): \App\Entity\Pointages
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setModifieLe', [$modifieLe]);

        return parent::setModifieLe($modifieLe);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription(?string $description): \App\Entity\Pointages
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getEtat(): ?array
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEtat', []);

        return parent::getEtat();
    }

    /**
     * {@inheritDoc}
     */
    public function setEtat(array $etat): \App\Entity\Pointages
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEtat', [$etat]);

        return parent::setEtat($etat);
    }

    /**
     * {@inheritDoc}
     */
    public function getTotalMinute(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotalMinute', []);

        return parent::getTotalMinute();
    }

    /**
     * {@inheritDoc}
     */
    public function setTotalMinute(?int $totalMinute): \App\Entity\Pointages
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotalMinute', [$totalMinute]);

        return parent::setTotalMinute($totalMinute);
    }

}
