<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class RightsDef extends \App\Entity\RightsDef implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\RightsDef' . "\0" . 'id', '' . "\0" . 'App\\Entity\\RightsDef' . "\0" . 'entity', '' . "\0" . 'App\\Entity\\RightsDef' . "\0" . 'libelle', '' . "\0" . 'App\\Entity\\RightsDef' . "\0" . 'module', '' . "\0" . 'App\\Entity\\RightsDef' . "\0" . 'perms', '' . "\0" . 'App\\Entity\\RightsDef' . "\0" . 'subperms', '' . "\0" . 'App\\Entity\\RightsDef' . "\0" . 'type', '' . "\0" . 'App\\Entity\\RightsDef' . "\0" . 'bydefault'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\RightsDef' . "\0" . 'id', '' . "\0" . 'App\\Entity\\RightsDef' . "\0" . 'entity', '' . "\0" . 'App\\Entity\\RightsDef' . "\0" . 'libelle', '' . "\0" . 'App\\Entity\\RightsDef' . "\0" . 'module', '' . "\0" . 'App\\Entity\\RightsDef' . "\0" . 'perms', '' . "\0" . 'App\\Entity\\RightsDef' . "\0" . 'subperms', '' . "\0" . 'App\\Entity\\RightsDef' . "\0" . 'type', '' . "\0" . 'App\\Entity\\RightsDef' . "\0" . 'bydefault'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (RightsDef $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getEntity(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getEntity();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEntity', []);

        return parent::getEntity();
    }

    /**
     * {@inheritDoc}
     */
    public function getLibelle(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLibelle', []);

        return parent::getLibelle();
    }

    /**
     * {@inheritDoc}
     */
    public function setLibelle(?string $libelle): \App\Entity\RightsDef
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLibelle', [$libelle]);

        return parent::setLibelle($libelle);
    }

    /**
     * {@inheritDoc}
     */
    public function getModule(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getModule', []);

        return parent::getModule();
    }

    /**
     * {@inheritDoc}
     */
    public function setModule(?string $module): \App\Entity\RightsDef
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setModule', [$module]);

        return parent::setModule($module);
    }

    /**
     * {@inheritDoc}
     */
    public function getPerms(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPerms', []);

        return parent::getPerms();
    }

    /**
     * {@inheritDoc}
     */
    public function setPerms(?string $perms): \App\Entity\RightsDef
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPerms', [$perms]);

        return parent::setPerms($perms);
    }

    /**
     * {@inheritDoc}
     */
    public function getSubperms(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSubperms', []);

        return parent::getSubperms();
    }

    /**
     * {@inheritDoc}
     */
    public function setSubperms(?string $subperms): \App\Entity\RightsDef
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSubperms', [$subperms]);

        return parent::setSubperms($subperms);
    }

    /**
     * {@inheritDoc}
     */
    public function getType(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getType', []);

        return parent::getType();
    }

    /**
     * {@inheritDoc}
     */
    public function setType(?string $type): \App\Entity\RightsDef
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setType', [$type]);

        return parent::setType($type);
    }

    /**
     * {@inheritDoc}
     */
    public function getBydefault(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBydefault', []);

        return parent::getBydefault();
    }

    /**
     * {@inheritDoc}
     */
    public function setBydefault(?bool $bydefault): \App\Entity\RightsDef
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBydefault', [$bydefault]);

        return parent::setBydefault($bydefault);
    }

}
