<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Employers extends \App\Entity\Employers implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Employers' . "\0" . 'rowid', '' . "\0" . 'App\\Entity\\Employers' . "\0" . 'nom', '' . "\0" . 'App\\Entity\\Employers' . "\0" . 'prenom', '' . "\0" . 'App\\Entity\\Employers' . "\0" . 'emailProfessionnel', '' . "\0" . 'App\\Entity\\Employers' . "\0" . 'telProfessionnel', '' . "\0" . 'App\\Entity\\Employers' . "\0" . 'situationMatrimonial', '' . "\0" . 'App\\Entity\\Employers' . "\0" . 'dateNaissance', '' . "\0" . 'App\\Entity\\Employers' . "\0" . 'lieuNaissance', '' . "\0" . 'App\\Entity\\Employers' . "\0" . 'sexe', '' . "\0" . 'App\\Entity\\Employers' . "\0" . 'adressePerso', '' . "\0" . 'App\\Entity\\Employers' . "\0" . 'nombreEnfant', '' . "\0" . 'App\\Entity\\Employers' . "\0" . 'numeroCnaps', '' . "\0" . 'App\\Entity\\Employers' . "\0" . 'numeroPassport', '' . "\0" . 'App\\Entity\\Employers' . "\0" . 'numeroCompteBancaire', '' . "\0" . 'App\\Entity\\Employers' . "\0" . 'numeroCin', '' . "\0" . 'App\\Entity\\Employers' . "\0" . 'numeroMatricule', '' . "\0" . 'App\\Entity\\Employers' . "\0" . 'numeroOstie', '' . "\0" . 'App\\Entity\\Employers' . "\0" . 'classification', '' . "\0" . 'App\\Entity\\Employers' . "\0" . 'nbrCongerRestant', '' . "\0" . 'App\\Entity\\Employers' . "\0" . 'dateVisiteMedicale', '' . "\0" . 'App\\Entity\\Employers' . "\0" . 'note', '' . "\0" . 'App\\Entity\\Employers' . "\0" . 'active', '' . "\0" . 'App\\Entity\\Employers' . "\0" . 'dateCreation', '' . "\0" . 'App\\Entity\\Employers' . "\0" . 'fkUser', '' . "\0" . 'App\\Entity\\Employers' . "\0" . 'fkSociete', '' . "\0" . 'App\\Entity\\Employers' . "\0" . 'fkNationalite', '' . "\0" . 'App\\Entity\\Employers' . "\0" . 'fkUserLie', '' . "\0" . 'App\\Entity\\Employers' . "\0" . 'fkDepartement', '' . "\0" . 'App\\Entity\\Employers' . "\0" . 'photo'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Employers' . "\0" . 'rowid', '' . "\0" . 'App\\Entity\\Employers' . "\0" . 'nom', '' . "\0" . 'App\\Entity\\Employers' . "\0" . 'prenom', '' . "\0" . 'App\\Entity\\Employers' . "\0" . 'emailProfessionnel', '' . "\0" . 'App\\Entity\\Employers' . "\0" . 'telProfessionnel', '' . "\0" . 'App\\Entity\\Employers' . "\0" . 'situationMatrimonial', '' . "\0" . 'App\\Entity\\Employers' . "\0" . 'dateNaissance', '' . "\0" . 'App\\Entity\\Employers' . "\0" . 'lieuNaissance', '' . "\0" . 'App\\Entity\\Employers' . "\0" . 'sexe', '' . "\0" . 'App\\Entity\\Employers' . "\0" . 'adressePerso', '' . "\0" . 'App\\Entity\\Employers' . "\0" . 'nombreEnfant', '' . "\0" . 'App\\Entity\\Employers' . "\0" . 'numeroCnaps', '' . "\0" . 'App\\Entity\\Employers' . "\0" . 'numeroPassport', '' . "\0" . 'App\\Entity\\Employers' . "\0" . 'numeroCompteBancaire', '' . "\0" . 'App\\Entity\\Employers' . "\0" . 'numeroCin', '' . "\0" . 'App\\Entity\\Employers' . "\0" . 'numeroMatricule', '' . "\0" . 'App\\Entity\\Employers' . "\0" . 'numeroOstie', '' . "\0" . 'App\\Entity\\Employers' . "\0" . 'classification', '' . "\0" . 'App\\Entity\\Employers' . "\0" . 'nbrCongerRestant', '' . "\0" . 'App\\Entity\\Employers' . "\0" . 'dateVisiteMedicale', '' . "\0" . 'App\\Entity\\Employers' . "\0" . 'note', '' . "\0" . 'App\\Entity\\Employers' . "\0" . 'active', '' . "\0" . 'App\\Entity\\Employers' . "\0" . 'dateCreation', '' . "\0" . 'App\\Entity\\Employers' . "\0" . 'fkUser', '' . "\0" . 'App\\Entity\\Employers' . "\0" . 'fkSociete', '' . "\0" . 'App\\Entity\\Employers' . "\0" . 'fkNationalite', '' . "\0" . 'App\\Entity\\Employers' . "\0" . 'fkUserLie', '' . "\0" . 'App\\Entity\\Employers' . "\0" . 'fkDepartement', '' . "\0" . 'App\\Entity\\Employers' . "\0" . 'photo'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Employers $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getRowid(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getRowid();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRowid', []);

        return parent::getRowid();
    }

    /**
     * {@inheritDoc}
     */
    public function getNom(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNom', []);

        return parent::getNom();
    }

    /**
     * {@inheritDoc}
     */
    public function setNom(string $nom): \App\Entity\Employers
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNom', [$nom]);

        return parent::setNom($nom);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrenom(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrenom', []);

        return parent::getPrenom();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrenom(?string $prenom): \App\Entity\Employers
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrenom', [$prenom]);

        return parent::setPrenom($prenom);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmailProfessionnel(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmailProfessionnel', []);

        return parent::getEmailProfessionnel();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmailProfessionnel(?string $emailProfessionnel): \App\Entity\Employers
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmailProfessionnel', [$emailProfessionnel]);

        return parent::setEmailProfessionnel($emailProfessionnel);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelProfessionnel(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelProfessionnel', []);

        return parent::getTelProfessionnel();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelProfessionnel(?string $telProfessionnel): \App\Entity\Employers
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelProfessionnel', [$telProfessionnel]);

        return parent::setTelProfessionnel($telProfessionnel);
    }

    /**
     * {@inheritDoc}
     */
    public function getSituationMatrimonial(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSituationMatrimonial', []);

        return parent::getSituationMatrimonial();
    }

    /**
     * {@inheritDoc}
     */
    public function setSituationMatrimonial(?string $situationMatrimonial): \App\Entity\Employers
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSituationMatrimonial', [$situationMatrimonial]);

        return parent::setSituationMatrimonial($situationMatrimonial);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateNaissance(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateNaissance', []);

        return parent::getDateNaissance();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateNaissance(\DateTimeInterface $dateNaissance): \App\Entity\Employers
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateNaissance', [$dateNaissance]);

        return parent::setDateNaissance($dateNaissance);
    }

    /**
     * {@inheritDoc}
     */
    public function getLieuNaissance(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLieuNaissance', []);

        return parent::getLieuNaissance();
    }

    /**
     * {@inheritDoc}
     */
    public function setLieuNaissance(?string $lieuNaissance): \App\Entity\Employers
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLieuNaissance', [$lieuNaissance]);

        return parent::setLieuNaissance($lieuNaissance);
    }

    /**
     * {@inheritDoc}
     */
    public function getSexe(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSexe', []);

        return parent::getSexe();
    }

    /**
     * {@inheritDoc}
     */
    public function setSexe(?string $sexe): \App\Entity\Employers
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSexe', [$sexe]);

        return parent::setSexe($sexe);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdressePerso(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdressePerso', []);

        return parent::getAdressePerso();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdressePerso(?string $adressePerso): \App\Entity\Employers
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdressePerso', [$adressePerso]);

        return parent::setAdressePerso($adressePerso);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombreEnfant(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombreEnfant', []);

        return parent::getNombreEnfant();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombreEnfant(?string $nombreEnfant): \App\Entity\Employers
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombreEnfant', [$nombreEnfant]);

        return parent::setNombreEnfant($nombreEnfant);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumeroCnaps(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumeroCnaps', []);

        return parent::getNumeroCnaps();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumeroCnaps(?string $numeroCnaps): \App\Entity\Employers
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumeroCnaps', [$numeroCnaps]);

        return parent::setNumeroCnaps($numeroCnaps);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumeroPassport(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumeroPassport', []);

        return parent::getNumeroPassport();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumeroPassport(?string $numeroPassport): \App\Entity\Employers
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumeroPassport', [$numeroPassport]);

        return parent::setNumeroPassport($numeroPassport);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumeroCompteBancaire(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumeroCompteBancaire', []);

        return parent::getNumeroCompteBancaire();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumeroCompteBancaire(?string $numeroCompteBancaire): \App\Entity\Employers
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumeroCompteBancaire', [$numeroCompteBancaire]);

        return parent::setNumeroCompteBancaire($numeroCompteBancaire);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumeroCin(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumeroCin', []);

        return parent::getNumeroCin();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumeroCin(?string $numeroCin): \App\Entity\Employers
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumeroCin', [$numeroCin]);

        return parent::setNumeroCin($numeroCin);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumeroMatricule(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumeroMatricule', []);

        return parent::getNumeroMatricule();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumeroMatricule(?string $numeroMatricule): \App\Entity\Employers
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumeroMatricule', [$numeroMatricule]);

        return parent::setNumeroMatricule($numeroMatricule);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumeroOstie(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumeroOstie', []);

        return parent::getNumeroOstie();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumeroOstie(?string $numeroOstie): \App\Entity\Employers
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumeroOstie', [$numeroOstie]);

        return parent::setNumeroOstie($numeroOstie);
    }

    /**
     * {@inheritDoc}
     */
    public function getClassification(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClassification', []);

        return parent::getClassification();
    }

    /**
     * {@inheritDoc}
     */
    public function setClassification(?string $classification): \App\Entity\Employers
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClassification', [$classification]);

        return parent::setClassification($classification);
    }

    /**
     * {@inheritDoc}
     */
    public function getNbrCongerRestant(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNbrCongerRestant', []);

        return parent::getNbrCongerRestant();
    }

    /**
     * {@inheritDoc}
     */
    public function setNbrCongerRestant(?float $nbrCongerRestant): \App\Entity\Employers
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNbrCongerRestant', [$nbrCongerRestant]);

        return parent::setNbrCongerRestant($nbrCongerRestant);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateVisiteMedicale(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateVisiteMedicale', []);

        return parent::getDateVisiteMedicale();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateVisiteMedicale(?\DateTimeInterface $dateVisiteMedicale): \App\Entity\Employers
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateVisiteMedicale', [$dateVisiteMedicale]);

        return parent::setDateVisiteMedicale($dateVisiteMedicale);
    }

    /**
     * {@inheritDoc}
     */
    public function getNote(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNote', []);

        return parent::getNote();
    }

    /**
     * {@inheritDoc}
     */
    public function setNote(?string $note): \App\Entity\Employers
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNote', [$note]);

        return parent::setNote($note);
    }

    /**
     * {@inheritDoc}
     */
    public function getActive(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActive', []);

        return parent::getActive();
    }

    /**
     * {@inheritDoc}
     */
    public function setActive(?bool $active): \App\Entity\Employers
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActive', [$active]);

        return parent::setActive($active);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateCreation(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateCreation', []);

        return parent::getDateCreation();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateCreation(?\DateTimeInterface $dateCreation): \App\Entity\Employers
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateCreation', [$dateCreation]);

        return parent::setDateCreation($dateCreation);
    }

    /**
     * {@inheritDoc}
     */
    public function getFkUser(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFkUser', []);

        return parent::getFkUser();
    }

    /**
     * {@inheritDoc}
     */
    public function setFkUser(int $fkUser): \App\Entity\Employers
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFkUser', [$fkUser]);

        return parent::setFkUser($fkUser);
    }

    /**
     * {@inheritDoc}
     */
    public function getFkSociete(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFkSociete', []);

        return parent::getFkSociete();
    }

    /**
     * {@inheritDoc}
     */
    public function setFkSociete(int $fkSociete): \App\Entity\Employers
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFkSociete', [$fkSociete]);

        return parent::setFkSociete($fkSociete);
    }

    /**
     * {@inheritDoc}
     */
    public function getFkNationalite(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFkNationalite', []);

        return parent::getFkNationalite();
    }

    /**
     * {@inheritDoc}
     */
    public function setFkNationalite(int $fkNationalite): \App\Entity\Employers
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFkNationalite', [$fkNationalite]);

        return parent::setFkNationalite($fkNationalite);
    }

    /**
     * {@inheritDoc}
     */
    public function getFkUserLie(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFkUserLie', []);

        return parent::getFkUserLie();
    }

    /**
     * {@inheritDoc}
     */
    public function setFkUserLie(int $fkUserLie): \App\Entity\Employers
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFkUserLie', [$fkUserLie]);

        return parent::setFkUserLie($fkUserLie);
    }

    /**
     * {@inheritDoc}
     */
    public function getFkDepartement(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFkDepartement', []);

        return parent::getFkDepartement();
    }

    /**
     * {@inheritDoc}
     */
    public function setFkDepartement(?int $fkDepartement): \App\Entity\Employers
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFkDepartement', [$fkDepartement]);

        return parent::setFkDepartement($fkDepartement);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhoto(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhoto', []);

        return parent::getPhoto();
    }

    /**
     * {@inheritDoc}
     */
    public function setPhoto(?string $photo): \App\Entity\Employers
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhoto', [$photo]);

        return parent::setPhoto($photo);
    }

}
